version: '3.9'

services:

  dev-db:
    image: postgres:15
    ports: 
    - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
  test-db:
    image: postgres:15
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: 1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080